STATE_LIST = [
    "Andaman & Nicobar Island",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Chandigarh",
    "UT of DNH and DD",
    "Delhi",
    "Goa",
    "Gujarat",
    "Himachal Pradesh",
    "Haryana",
    "Jharkhand",
    "Jammu and Kashmir",
    "Karnataka",
    "Kerala",
    "Ladakh",
    "Lakshadweep",
    "Maharashtra",
    "Meghalaya",
    "Manipur",
    "Madhya Pradesh",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Puducherry",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttarakhand",
    "Uttar Pradesh",
    "West Bengal",
]


COMMON_FUEL_COLUMN_RENAME_MAP = {
    "BIO-CNG/BIO-GAS": "bio_cng_bio_gas",
    "BIO-DIESEL(B100)": "bio_diesel_b100",
    "BIO-METHANE": "bio_methane",
    "CNG ONLY": "cng_only",
    "DIESEL": "diesel",
    "DIESEL/HYBRID": "diesel_hybrid",
    "DI-METHYL ETHER": "di_methyl_ether",
    "DUAL DIESEL/BIO CNG": "dual_diesel_bio_cng",
    "DUAL DIESEL/CNG": "dual_diesel_cng",
    "DUAL DIESEL/LNG": "dual_diesel_lng",
    "ELECTRIC(BOV)": "electric_bov",
    "ETHANOL(E100)": "ethanol_e100",
    "FLEX-FUEL(BIO-DIESEL)": "flex_fuel_bio_diesel",
    "FLEX-FUEL(ETHANOL)": "flex_fuel_ethanol",
    "FUEL CELL HYDROGEN": "fuel_cell_hydrogen",
    "HCNG": "hcng",
    "HYDROGEN(ICE)": "hydrogen_ice",
    "LNG": "lng",
    "LPG ONLY": "lpg_only",
    "METHANOL": "methanol",
    "NOT APPLICABLE": "not_applicable",
    "PETROL": "petrol",
    "PETROL/CNG": "petrol_cng",
    "PETROL(E20)": "petrol_e20",
    "PETROL(E20)/CNG": "petrol_e20_cng",
    "PETROL(E20)/HYBRID": "petrol_e20_hybrid",
    "PETROL(E20)/HYBRID/CNG": "petrol_e20_hybrid_cng",
    "PETROL(E20)/LPG": "petrol_e20_lpg",
    "PETROL/HYBRID": "petrol_hybrid",
    "PETROL/HYBRID/CNG": "petrol_hybrid_cng",
    "PETROL/LPG": "petrol_lpg",
    "PETROL/METHANOL": "petrol_methanol",
    "PLUG-IN HYBRID EV": "plug_in_hybrid_ev",
    "PURE EV": "pure_ev",
    "SOLAR": "solar",
    "STRONG HYBRID EV": "strong_hybrid_ev",
    "Unnamed: 38": "total",
}
