STATE_LIST = [
    "Andaman & Nicobar Island",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Chandigarh",
    "UT of DNH and DD",
    "Delhi",
    "Goa",
    "Gujarat",
    "Himachal Pradesh",
    "Haryana",
    "Jharkhand",
    "Jammu and Kashmir",
    "Karnataka",
    "Kerala",
    "Ladakh",
    "Lakshadweep",
    "Maharashtra",
    "Meghalaya",
    "Manipur",
    "Madhya Pradesh",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Puducherry",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttarakhand",
    "Uttar Pradesh",
    "West Bengal",
]

# Maps each STATE_LIST entry (the full Vahan state name used throughout the
# existing pipelines) to the 2-letter stateCode the new Parivahan Analytics
# portal expects. Sourced from the portal's own state dropdown
# (analytics.parivahan.gov.in/analytics/publicdashboard/vahan), confirmed
# 1:1 against STATE_LIST on 2026-08-13. "Jammu and Kashmir" vs the portal's
# "Jammu & Kashmir" and "UT of DNH and DD" are the only name-spelling
# differences; the code mapping itself is unambiguous.
STATE_NAME_TO_NEW_PORTAL_CODE = {
    "Andaman & Nicobar Island": "AN",
    "Andhra Pradesh": "AP",
    "Arunachal Pradesh": "AR",
    "Assam": "AS",
    "Bihar": "BR",
    "Chhattisgarh": "CG",
    "Chandigarh": "CH",
    "UT of DNH and DD": "DD",
    "Delhi": "DL",
    "Goa": "GA",
    "Gujarat": "GJ",
    "Himachal Pradesh": "HP",
    "Haryana": "HR",
    "Jharkhand": "JH",
    "Jammu and Kashmir": "JK",
    "Karnataka": "KA",
    "Kerala": "KL",
    "Ladakh": "LA",
    "Lakshadweep": "LD",
    "Maharashtra": "MH",
    "Meghalaya": "ML",
    "Manipur": "MN",
    "Madhya Pradesh": "MP",
    "Mizoram": "MZ",
    "Nagaland": "NL",
    "Odisha": "OR",
    "Punjab": "PB",
    "Puducherry": "PY",
    "Rajasthan": "RJ",
    "Sikkim": "SK",
    "Tamil Nadu": "TN",
    "Telangana": "TG",
    "Tripura": "TR",
    "Uttarakhand": "UK",
    "Uttar Pradesh": "UP",
    "West Bengal": "WB",
    # The two aliases below are NOT in STATE_LIST — they're the literal
    # strings found in fact_ev_data_by_rto.state for these two union
    # territories, which differ from STATE_LIST's spelling. Discovered
    # 2026-08-13 building the RTO crosswalk (4 legacy RTOs went unmatched
    # until these were added). Keep both the STATE_LIST spelling and the
    # DB's actual spelling mapped, since callers may key off either.
    "Andaman and Nicobar": "AN",
    "Dadara and Nagar Havelli": "DD",
}

MONTH_NAME_TO_NUMBER = {
    "JAN": 1,
    "FEB": 2,
    "MAR": 3,
    "APR": 4,
    "MAY": 5,
    "JUN": 6,
    "JUL": 7,
    "AUG": 8,
    "SEP": 9,
    "OCT": 10,
    "NOV": 11,
    "DEC": 12,
}


COMMON_FUEL_COLUMN_RENAME_MAP = {
    "BIO-CNG/BIO-GAS": "bio_cng_bio_gas",
    "BIO-DIESEL(B100)": "bio_diesel_b100",
    "BIO-METHANE": "bio_methane",
    "CNG ONLY": "cng_only",
    "DIESEL": "diesel",
    "DIESEL/HYBRID": "diesel_hybrid",
    "DI-METHYL ETHER": "di_methyl_ether",
    "DUAL DIESEL/BIO CNG": "dual_diesel_bio_cng",
    "DUAL DIESEL/CNG": "dual_diesel_cng",
    "DUAL DIESEL/LNG": "dual_diesel_lng",
    "ELECTRIC(BOV)": "electric_bov",
    "ETHANOL(E100)": "ethanol_e100",
    "FLEX-FUEL(BIO-DIESEL)": "flex_fuel_bio_diesel",
    "FLEX-FUEL(ETHANOL)": "flex_fuel_ethanol",
    "FUEL CELL HYDROGEN": "fuel_cell_hydrogen",
    "HCNG": "hcng",
    "HYDROGEN(ICE)": "hydrogen_ice",
    "LNG": "lng",
    "LPG ONLY": "lpg_only",
    "METHANOL": "methanol",
    "NOT APPLICABLE": "not_applicable",
    "PETROL": "petrol",
    "PETROL/CNG": "petrol_cng",
    "PETROL(E20)": "petrol_e20",
    "PETROL(E20)/CNG": "petrol_e20_cng",
    "PETROL(E20)/HYBRID": "petrol_e20_hybrid",
    "PETROL(E20)/HYBRID/CNG": "petrol_e20_hybrid_cng",
    "PETROL(E20)/LPG": "petrol_e20_lpg",
    "PETROL/HYBRID": "petrol_hybrid",
    "PETROL/HYBRID/CNG": "petrol_hybrid_cng",
    "PETROL/LPG": "petrol_lpg",
    "PETROL/METHANOL": "petrol_methanol",
    "PLUG-IN HYBRID EV": "plug_in_hybrid_ev",
    "PURE EV": "pure_ev",
    "SOLAR": "solar",
    "STRONG HYBRID EV": "strong_hybrid_ev",
    "Unnamed: 38": "total",
}
